server:
  port: 8089

spring:
  application:
    name: novaswap-service

logging:
  level:
    root: INFO
    com.novaswap: DEBUG

novaswap:
  rpcUrl: https://mainnet.infura.io/v3/YOUR_KEY
  chainId: 1
  privateKey: ""
  gasPriceGwei: 15
  gasLimit: 2000000
  contract:
    factory: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
    router: "0xRouterAddress"
    weth: "0xWETHAddress"
    multicall: "0xcA11bde05977b3631167028862bE2a173976CA11" # Multicall3 Universal Address
  
  # 多链网络配置
  networks:
    ethereum:
      chainId: 1
      rpcUrl: https://mainnet.infura.io/v3/YOUR_KEY
      router: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
      weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
    arbitrum:
      chainId: 42161
      rpcUrl: https://arb1.arbitrum.io/rpc
      router: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
      weth: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
      multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
    optimism:
      chainId: 10
      rpcUrl: https://mainnet.optimism.io
      router: "0x4A7b5Da61326A6379179b40d00F57E5bbDC962c2"
      weth: "0x4200000000000000000000000000000000000006"
      multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
    polygon:
      chainId: 137
      rpcUrl: https://polygon-rpc.com
      router: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
      weth: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
      multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
    bsc:
      chainId: 56
      rpcUrl: https://bsc-dataseed.binance.org
      router: "0x10ED43C718714eb63d5aA57B78B54704E256024E"
      weth: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
      multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
    avalanche:
      chainId: 43114
      rpcUrl: https://api.avax.network/ext/bc/C/rpc
      router: "0x60aE616a2155Ee3d9A68541Ba4544862310933d4"
      weth: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
      multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
    zetachain:
      chainId: 7000
      rpcUrl: https://zetachain-evm.blockpi.network/v1/rpc/public
      router: "0x2ca7d64A7EFE2D62A725E2B35Cf7230D6677FfEe"
      weth: "0x5F0b1a82749cb4E2278EC87F8BF6B618dC71a8bf"
      multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
